### PR TITLE
Gradual information deletion on the sync server

### PR DESCRIPTION
**Pull request by darosior**
I speak for all of us in this one, please ack (or nack if this is nonsensical).

### CODE REVIEW

**Review by JSwambo — APPROVED** [review]
There are two aspects to the security model worth considering here. First, the sync server is not trusted to secure funds, so it is reasonable to allow outsourcing it. Second, the sync server is _critical_ for timely operations (especially with the current fallback to manual fund management if sync server drops out), so it is highly unlikely IMO that an organization will want to outsource this.  

In either case, gradual information deletion makes sense to me.

ack a1d28e802c70da5c3d11e46a18c3b30e97c310f8

**Comment by darosior** [comment]
Yeah maybe i should have done a clear separation instead of sneaking it in.

Interesting, i disagree. I think they'll outsource to people more competent to guarantee their timely operations than they are: invoices are cheaper than a dedicated tech team.

**Comment by kloaec** [comment]
I need to think about this a bit more.
Indeed the sync server SHOULD be untrusted. It is a vector of DOS though, by itself or to the wallets I guess depending on message formats (could spam requests/notifications of signatures).

Regarding the original point: yes I suppose we can delete info regularly, no problem.

**Comment by kloaec** [comment]
ack a1d28e802c70da5c3d11e46a18c3b30e97c310f8

**Review by edouardparis — APPROVED** [review]
ACK a1d28e802c70da5c3d11e46a18c3b30e97c310f8

**Pull request merged**
