### PR TITLE
messages: remove watchtower opinion polling

### PR DESCRIPTION
**Pull request by darosior**
This is sooooooo much cleaner without this complexity. Whose idea was it already?

### CODE REVIEW

**Review by edouardparis — APPROVED** [review]
Keep it simple :clap: 
ACK 1a4da351fcdb30da3e994ba8f3434cece0d4882b

**Review by JSwambo — APPROVED** [review]
Ack 1a4da351fcdb30da3e994ba8f3434cece0d4882b

**Comment by darosior** [comment]
Lol guys i dropped half the spending process doc.. Arg we should have catched it! :)

**Review by kloaec — COMMENTED** [review]
Sorry for the late ack, but yes, much cleaner.

We need some kind of "delay" between asking the coordinator and triggering the cancel if no or wrong reply. Short but not stupidly short. Also might be a config option?

Also a fallback coordinator really makes sense here, if first one isn't responding (especially for external WT like the Revault corp ones.

**Comment by darosior** [comment]
delay: yea, it would make sense to make it configurable. I think a fraction of the CSV delay would be a sensible default (2%? With a 12 blocks CSV it's `(12 - 1) / 10 = 2.2` seconds, with -1 accounting for the worst case event of a block being found just after our poll).

re fallback coordinator: definitely.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
